from sqlalchemy import Numeric, Table, Column, ForeignKey
from sqlalchemy.sql.sqltypes import Integer, String
from config.db import meta

automoviles = Table("automoviles", meta, Column("ingresado_por", String(255)),
                    Column(
    "id", Integer, primary_key=True, index=True),
    Column("marca", String(255)),
    Column("fecha_ingreso", String(255)),
    Column("orden_pago", Integer, nullable=True),
    Column("partida_compra", Integer, nullable=True),
    Column("num_factura", Integer, nullable=True),
    Column("modelo", String(2000)),
    Column("valor_inicial", Numeric(40, 3)),
    Column("valor_actual", Numeric(40, 3)),
    Column("num_bien", Integer),
    Column("num_serial_motor", String(255)),
    Column("num_serial_carroceria", String(255)),
    Column("num_expediente", String(255)),
    Column("departamento", String(255)),
    Column("chofer", String(255)),
    Column("año", Integer),
    Column("color", String(255)),
    Column("placa", String(255)),
    Column("estatus", String(255)),
    Column("operatividad", String(255)),
    Column("concepto_incorporacion", String(20), ForeignKey("conceptos_movimiento.codigo")),
)

automovilesDeleted = Table("deleted_automoviles", meta,
    Column("ingresado_por", String(255)),
    Column("eliminado_por", String(255)), 
    Column(
    "id", Integer, primary_key=True, index=True),
    Column("fecha_ingreso", String(255)),
    Column("orden_pago", Integer, nullable=True),
    Column("partida_compra", Integer, nullable=True),
    Column("num_factura", Integer, nullable=True),
    Column("marca", String(255)),
    Column("modelo", String(2000)),
    Column("valor_inicial", Numeric(40, 3)),
    Column("valor_actual", Numeric(40, 3)),
    Column("num_bien", Integer),
    Column("num_oficio", Integer),
    Column("num_serial_motor", String(255)),
    Column("num_serial_carroceria", String(255)),
    Column("num_expediente", String(255)),
    Column("departamento", String(255)),
    Column("año", Integer),
    Column("color", String(255)),
    Column("placa", String(255)),
    Column("estatus", String(255)),
    Column("operatividad", String(255)),
    Column("concepto_incorporacion", String(20)),
    Column("concepto_desincorporacion", String(20)),
    )
