from sqlalchemy import Numeric, Table, Column, ForeignKey
from sqlalchemy.sql.sqltypes import Integer, String
from config.db import meta

muebles = Table("muebles", meta, Column(
    "id", Integer, primary_key=True, index=True),
    Column("fecha_ingreso", String(255)),
    Column("fecha_compra", String(255)),
    Column("orden_pago", Integer, nullable=True),
    Column("partida_compra", Integer, nullable=True),
    Column("num_factura", Integer, nullable=True),
    Column("num_catalogo", String(255)),
    Column("esTecnologia", Integer),
    Column("descripcion", String(2000)),
    Column("marca", String(2000)),
    Column("modelo", String(2000)),
    Column("serial", String(2000)),
    Column("responsable", String(2000)),
    Column("estado", String(2000)),
    Column("valor_inicial", Numeric(40, 3)),
    Column("valor_actual", Numeric(40, 3)),
    Column("num_bien", Integer),
    Column("departamento", String(255)),
    Column("concepto_incorporacion", String(20), ForeignKey("conceptos_movimiento.codigo")),
    Column("ingresado_por", String(255)))

mueblesDeleted = Table("deleted_muebles", meta, Column(
    "id", Integer, primary_key=True, index=True),
    Column("fecha_ingreso", String(255)),
    Column("fecha_compra", String(255)),
    Column("orden_pago", Integer, nullable=True),
    Column("partida_compra", Integer, nullable=True),
    Column("num_factura", Integer, nullable=True),
    Column("num_catalogo", String(255)),
    Column("esTecnologia", Integer),
    Column("marca", String(2000)),
    Column("modelo", String(2000)),
    Column("serial", String(2000)),
    Column("responsable", String(2000)),
    Column("estado", String(2000)),
    Column("descripcion", String(2000)),
    Column("valor_inicial", Numeric(40, 3)),
    Column("valor_actual", Numeric(40, 3)),
    Column("num_bien", Integer),
    Column("num_oficio", Integer),
    Column("departamento", String(255)),
    Column("eliminado_por", String(255)),
    Column("concepto_incorporacion", String(20)),
    Column("concepto_desincorporacion", String(20)),
    Column("ingresado_por", String(255)))

mueblesTecnologia = Table("muebles_tecnologia", meta, Column(
    "id", Integer, primary_key=True, index=True),
    Column("fecha_ingreso", String(255)),
    Column("fecha_compra", String(255)),
    Column("orden_pago", Integer, nullable=True),
    Column("partida_compra", Integer, nullable=True),
    Column("num_factura", Integer, nullable=True),
    Column("num_catalogo", String(255)),
    Column("esTecnologia", Integer),
    Column("descripcion", String(2000)),
    Column("marca", String(2000)),
    Column("modelo", String(2000)),
    Column("serial", String(2000)),
    Column("responsable", String(2000)),
    Column("estado", String(2000)),
    Column("valor_inicial", Numeric(40, 3)),
    Column("valor_actual", Numeric(40, 3)),
    Column("num_bien", Integer),
    Column("departamento", String(255)),
    Column("concepto_incorporacion", String(20), ForeignKey("conceptos_movimiento.codigo")),
    Column("ingresado_por", String(255)))
